version: '2.4'

services:
  db:
    image: postgres
    volumes:
      - gsn-data:/var/lib/postgresql/data/
  web:
    build: .
    entrypoint: "/code/docker-entrypoint.sh"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=developerkey
    depends_on:
      - db

volumes:
  gsn-data:
