version: '2.4'

services:
  db:
    image: postgres
    volumes:
      - gsn-data:/var/lib/postgresql/data/
  gsn_web:
    build: 
      context: .
      dockerfile: Dockerfile-django
    volumes:
      - .:/code
    expose:
      - "80"
    ports:
      - 80:80
    environment:
      - SECRET_KEY=developerkey
    depends_on:
      - db

volumes:
  gsn-data:
